package admin

import (
	"bytes"
	"context"
	"errors"
	"path/filepath"
	"testing"

	"github.com/infodancer/maildancer/auth"
	"github.com/infodancer/maildancer/auth/passwd"
	"github.com/infodancer/maildancer/msgstore"
)

// authenticate runs a real passwd-agent authentication against the domain's
// credential and key files, returning the session (caller clears it).
func authenticate(t *testing.T, p Paths, domain, username, password string) (*auth.AuthSession, error) {
	t.Helper()
	agent, err := passwd.NewAgent(
		filepath.Join(p.Config, domain, "passwd"),
		filepath.Join(p.Config, domain, "keys"))
	if err != nil {
		t.Fatalf("NewAgent: %v", err)
	}
	agent = agent.WithUserKeyringBase(filepath.Join(p.Data, domain, "users"))
	defer func() { _ = agent.Close() }()
	return agent.Authenticate(context.Background(), username, password)
}

// newKeyedUser creates example.com with alice (password old-password-123) and
// a generated keypair, returning the configured Paths.
func newKeyedUser(t *testing.T) Paths {
	t.Helper()
	p := newTestPaths(t)
	if _, err := p.CreateDomain("example.com"); err != nil {
		t.Fatal(err)
	}
	if _, err := p.CreateUser("example.com", "alice", "old-password-123", true); err != nil {
		t.Fatal(err)
	}
	return p
}

// TestAdminKeysAuthRoundTrip pins format compatibility between
// internal/admin/keys (provisioning) and auth/passwd (authentication): a
// keypair generated by admin tooling must unseal at login, and the unsealed
// private key must decrypt a message encrypted to the stored public key.
// The Argon2id parameters are duplicated in both packages; this test makes
// drift loud.
func TestAdminKeysAuthRoundTrip(t *testing.T) {
	p := newKeyedUser(t)

	session, err := authenticate(t, p, "example.com", "alice", "old-password-123")
	if err != nil {
		t.Fatalf("Authenticate against admin-provisioned keys: %v", err)
	}
	defer session.Clear()
	if !session.EncryptionEnabled || len(session.PrivateKey) != 32 {
		t.Fatalf("want encryption-enabled session with 32-byte key, got enabled=%v len=%d",
			session.EncryptionEnabled, len(session.PrivateKey))
	}

	plaintext := []byte("round trip through provisioning, auth, and msgstore crypto")
	encrypted, err := msgstore.EncryptMessage(plaintext, session.PublicKey)
	if err != nil {
		t.Fatalf("EncryptMessage with stored public key: %v", err)
	}
	decrypted, err := msgstore.DecryptMessage(encrypted, session.PrivateKey)
	if err != nil {
		t.Fatalf("DecryptMessage with unsealed private key: %v", err)
	}
	if !bytes.Equal(decrypted, plaintext) {
		t.Error("round trip mismatch")
	}
}

func TestChangePassword_RekeysSealedKey(t *testing.T) {
	p := newKeyedUser(t)

	before, err := p.UserKeyStatus("example.com", "alice")
	if err != nil || !before.Exists {
		t.Fatalf("key status before: %+v err=%v", before, err)
	}

	if err := p.ChangePassword("example.com", "alice", "old-password-123", "new-password-456"); err != nil {
		t.Fatalf("ChangePassword: %v", err)
	}

	// Old password no longer authenticates.
	if _, err := authenticate(t, p, "example.com", "alice", "old-password-123"); err == nil {
		t.Error("old password still authenticates after change")
	}

	// New password authenticates AND unseals the key -- no lockout, no
	// orphaned key, same keypair (fingerprint unchanged, old mail readable).
	session, err := authenticate(t, p, "example.com", "alice", "new-password-456")
	if err != nil {
		t.Fatalf("authenticate with new password: %v", err)
	}
	defer session.Clear()
	if !session.EncryptionEnabled || len(session.PrivateKey) != 32 {
		t.Fatal("key did not survive the password change")
	}

	after, err := p.UserKeyStatus("example.com", "alice")
	if err != nil {
		t.Fatal(err)
	}
	if after.Fingerprint != before.Fingerprint {
		t.Errorf("fingerprint changed: %s -> %s (keypair must be preserved)", before.Fingerprint, after.Fingerprint)
	}
}

func TestChangePassword_WrongOldPassword(t *testing.T) {
	p := newKeyedUser(t)

	err := p.ChangePassword("example.com", "alice", "not-the-password", "new-password-456")
	if err == nil {
		t.Fatal("ChangePassword with wrong old password must fail")
	}

	// Nothing changed: old password still works and unseals the key.
	session, err := authenticate(t, p, "example.com", "alice", "old-password-123")
	if err != nil {
		t.Fatalf("original password broken after failed change: %v", err)
	}
	session.Clear()
}

func TestChangePassword_KeylessUser(t *testing.T) {
	p := newTestPaths(t)
	if _, err := p.CreateDomain("example.com"); err != nil {
		t.Fatal(err)
	}
	if _, err := p.CreateUser("example.com", "bob", "old-password-123", false); err != nil {
		t.Fatal(err)
	}

	if err := p.ChangePassword("example.com", "bob", "old-password-123", "new-password-456"); err != nil {
		t.Fatalf("ChangePassword keyless: %v", err)
	}
	session, err := authenticate(t, p, "example.com", "bob", "new-password-456")
	if err != nil {
		t.Fatalf("authenticate with new password: %v", err)
	}
	session.Clear()
}

func TestResetPassword_RefusesKeyedUser(t *testing.T) {
	p := newKeyedUser(t)

	err := p.ResetPassword("example.com", "alice", "new-password-456")
	if !errors.Is(err, ErrUserHasKeys) {
		t.Fatalf("ResetPassword on keyed user: want ErrUserHasKeys, got %v", err)
	}

	// Refusal must not have touched the hash.
	session, err := authenticate(t, p, "example.com", "alice", "old-password-123")
	if err != nil {
		t.Fatalf("original password broken after refused reset: %v", err)
	}
	session.Clear()
}

func TestResetPassword_KeylessUserUnchanged(t *testing.T) {
	p := newTestPaths(t)
	if _, err := p.CreateDomain("example.com"); err != nil {
		t.Fatal(err)
	}
	if _, err := p.CreateUser("example.com", "bob", "old-password-123", false); err != nil {
		t.Fatal(err)
	}
	if err := p.ResetPassword("example.com", "bob", "new-password-456"); err != nil {
		t.Fatalf("ResetPassword keyless: %v", err)
	}
	session, err := authenticate(t, p, "example.com", "bob", "new-password-456")
	if err != nil {
		t.Fatalf("authenticate with new password: %v", err)
	}
	session.Clear()
}

func TestResetPasswordRegenKeys(t *testing.T) {
	p := newKeyedUser(t)

	before, err := p.UserKeyStatus("example.com", "alice")
	if err != nil || !before.Exists {
		t.Fatalf("key status before: %+v err=%v", before, err)
	}

	fingerprint, err := p.ResetPasswordRegenKeys("example.com", "alice", "new-password-456")
	if err != nil {
		t.Fatalf("ResetPasswordRegenKeys: %v", err)
	}
	if fingerprint == "" {
		t.Fatal("want new fingerprint for keyed user")
	}
	if fingerprint == before.Fingerprint {
		t.Error("fingerprint unchanged -- keypair must be regenerated, not reused")
	}

	// New password authenticates and unseals the NEW key. No lockout.
	session, err := authenticate(t, p, "example.com", "alice", "new-password-456")
	if err != nil {
		t.Fatalf("authenticate after regen: %v", err)
	}
	defer session.Clear()
	if !session.EncryptionEnabled || len(session.PrivateKey) != 32 {
		t.Fatal("regenerated key did not unseal at login")
	}
}

func TestResetPasswordRegenKeys_KeylessUser(t *testing.T) {
	// A keyless user gets a plain hash reset; no keypair is invented.
	p := newTestPaths(t)
	if _, err := p.CreateDomain("example.com"); err != nil {
		t.Fatal(err)
	}
	if _, err := p.CreateUser("example.com", "bob", "old-password-123", false); err != nil {
		t.Fatal(err)
	}

	fingerprint, err := p.ResetPasswordRegenKeys("example.com", "bob", "new-password-456")
	if err != nil {
		t.Fatalf("ResetPasswordRegenKeys keyless: %v", err)
	}
	if fingerprint != "" {
		t.Errorf("keyless user must not gain keys from a password reset, got fingerprint %q", fingerprint)
	}
	status, _ := p.UserKeyStatus("example.com", "bob")
	if status.Exists {
		t.Error("keypair fabricated for keyless user")
	}
}
