// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mailsession/v1/delivery.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliverResult indicates the outcome of a delivery attempt.
type DeliverResult int32

const (
	DeliverResult_DELIVER_RESULT_UNSPECIFIED DeliverResult = 0
	// Message was successfully written to the maildir.
	DeliverResult_DELIVER_RESULT_DELIVERED DeliverResult = 1
	// Delivery was refused. Check temporary and reason fields.
	DeliverResult_DELIVER_RESULT_REJECTED DeliverResult = 2
	// Message should be delivered to redirect_addresses instead.
	// The dispatcher re-delivers with forwarded=true (1-hop limit).
	DeliverResult_DELIVER_RESULT_REDIRECTED DeliverResult = 3
)

// Enum value maps for DeliverResult.
var (
	DeliverResult_name = map[int32]string{
		0: "DELIVER_RESULT_UNSPECIFIED",
		1: "DELIVER_RESULT_DELIVERED",
		2: "DELIVER_RESULT_REJECTED",
		3: "DELIVER_RESULT_REDIRECTED",
	}
	DeliverResult_value = map[string]int32{
		"DELIVER_RESULT_UNSPECIFIED": 0,
		"DELIVER_RESULT_DELIVERED":   1,
		"DELIVER_RESULT_REJECTED":    2,
		"DELIVER_RESULT_REDIRECTED":  3,
	}
)

func (x DeliverResult) Enum() *DeliverResult {
	p := new(DeliverResult)
	*p = x
	return p
}

func (x DeliverResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliverResult) Descriptor() protoreflect.EnumDescriptor {
	return file_mailsession_v1_delivery_proto_enumTypes[0].Descriptor()
}

func (DeliverResult) Type() protoreflect.EnumType {
	return &file_mailsession_v1_delivery_proto_enumTypes[0]
}

func (x DeliverResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliverResult.Descriptor instead.
func (DeliverResult) EnumDescriptor() ([]byte, []int) {
	return file_mailsession_v1_delivery_proto_rawDescGZIP(), []int{0}
}

// DeliverRequest is client-streaming: metadata first, then body chunks.
type DeliverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DeliverRequest_Metadata
	//	*DeliverRequest_Data
	Payload       isDeliverRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_mailsession_v1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverRequest) GetPayload() isDeliverRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeliverRequest) GetMetadata() *DeliverMetadata {
	if x != nil {
		if x, ok := x.Payload.(*DeliverRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DeliverRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*DeliverRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDeliverRequest_Payload interface {
	isDeliverRequest_Payload()
}

type DeliverRequest_Metadata struct {
	// First message in the stream carries delivery metadata.
	Metadata *DeliverMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DeliverRequest_Data struct {
	// Subsequent messages carry raw message body chunks.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DeliverRequest_Metadata) isDeliverRequest_Payload() {}

func (*DeliverRequest_Data) isDeliverRequest_Payload() {}

// DeliverMetadata carries the envelope information for delivery.
type DeliverMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender is the MAIL FROM reverse-path (may be empty for bounces).
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Recipient is the RCPT TO forward-path (single recipient per delivery).
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Client IP address of the submitting MTA.
	ClientIp string `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// EHLO/HELO hostname from the submitting MTA.
	ClientHostname string `protobuf:"bytes,4,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	// When true, forwarding resolution is skipped (1-hop limit enforcement).
	Forwarded bool `protobuf:"varint,5,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	// Identifies the recipient's public key for at-rest encryption.
	// Empty means no encryption. Resolved by the KeyProvider in auth.
	EncryptionKeyHint string `protobuf:"bytes,6,opt,name=encryption_key_hint,json=encryptionKeyHint,proto3" json:"encryption_key_hint,omitempty"`
	// When the message was accepted by the upstream daemon (RFC 3339).
	ReceivedTime  string `protobuf:"bytes,7,opt,name=received_time,json=receivedTime,proto3" json:"received_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMetadata) Reset() {
	*x = DeliverMetadata{}
	mi := &file_mailsession_v1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMetadata) ProtoMessage() {}

func (x *DeliverMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMetadata.ProtoReflect.Descriptor instead.
func (*DeliverMetadata) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverMetadata) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DeliverMetadata) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DeliverMetadata) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DeliverMetadata) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *DeliverMetadata) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

func (x *DeliverMetadata) GetEncryptionKeyHint() string {
	if x != nil {
		return x.EncryptionKeyHint
	}
	return ""
}

func (x *DeliverMetadata) GetReceivedTime() string {
	if x != nil {
		return x.ReceivedTime
	}
	return ""
}

// DeliverResponse is the outcome of the delivery pipeline.
type DeliverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The delivery result.
	Result DeliverResult `protobuf:"varint,1,opt,name=result,proto3,enum=mailsession.v1.DeliverResult" json:"result,omitempty"`
	// True for temporary failures (4xx); false for permanent (5xx).
	// Only meaningful when result is REJECTED.
	Temporary bool `protobuf:"varint,2,opt,name=temporary,proto3" json:"temporary,omitempty"`
	// Human-readable reason for rejection (logging only, not sent to remote MTA).
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Redirect target addresses when result is REDIRECTED.
	RedirectAddresses []string `protobuf:"bytes,4,rep,name=redirect_addresses,json=redirectAddresses,proto3" json:"redirect_addresses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_mailsession_v1_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverResponse) GetResult() DeliverResult {
	if x != nil {
		return x.Result
	}
	return DeliverResult_DELIVER_RESULT_UNSPECIFIED
}

func (x *DeliverResponse) GetTemporary() bool {
	if x != nil {
		return x.Temporary
	}
	return false
}

func (x *DeliverResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DeliverResponse) GetRedirectAddresses() []string {
	if x != nil {
		return x.RedirectAddresses
	}
	return nil
}

var File_mailsession_v1_delivery_proto protoreflect.FileDescriptor

const file_mailsession_v1_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1dmailsession/v1/delivery.proto\x12\x0emailsession.v1\"p\n" +
	"\x0eDeliverRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.mailsession.v1.DeliverMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x80\x02\n" +
	"\x0fDeliverMetadata\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12'\n" +
	"\x0fclient_hostname\x18\x04 \x01(\tR\x0eclientHostname\x12\x1c\n" +
	"\tforwarded\x18\x05 \x01(\bR\tforwarded\x12.\n" +
	"\x13encryption_key_hint\x18\x06 \x01(\tR\x11encryptionKeyHint\x12#\n" +
	"\rreceived_time\x18\a \x01(\tR\freceivedTime\"\xad\x01\n" +
	"\x0fDeliverResponse\x125\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1d.mailsession.v1.DeliverResultR\x06result\x12\x1c\n" +
	"\ttemporary\x18\x02 \x01(\bR\ttemporary\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12-\n" +
	"\x12redirect_addresses\x18\x04 \x03(\tR\x11redirectAddresses*\x89\x01\n" +
	"\rDeliverResult\x12\x1e\n" +
	"\x1aDELIVER_RESULT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DELIVER_RESULT_DELIVERED\x10\x01\x12\x1b\n" +
	"\x17DELIVER_RESULT_REJECTED\x10\x02\x12\x1d\n" +
	"\x19DELIVER_RESULT_REDIRECTED\x10\x032_\n" +
	"\x0fDeliveryService\x12L\n" +
	"\aDeliver\x12\x1e.mailsession.v1.DeliverRequest\x1a\x1f.mailsession.v1.DeliverResponse(\x01BMZKgithub.com/infodancer/maildancer/internal/mail-session/proto/mailsession/v1b\x06proto3"

var (
	file_mailsession_v1_delivery_proto_rawDescOnce sync.Once
	file_mailsession_v1_delivery_proto_rawDescData []byte
)

func file_mailsession_v1_delivery_proto_rawDescGZIP() []byte {
	file_mailsession_v1_delivery_proto_rawDescOnce.Do(func() {
		file_mailsession_v1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailsession_v1_delivery_proto_rawDesc), len(file_mailsession_v1_delivery_proto_rawDesc)))
	})
	return file_mailsession_v1_delivery_proto_rawDescData
}

var file_mailsession_v1_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mailsession_v1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mailsession_v1_delivery_proto_goTypes = []any{
	(DeliverResult)(0),      // 0: mailsession.v1.DeliverResult
	(*DeliverRequest)(nil),  // 1: mailsession.v1.DeliverRequest
	(*DeliverMetadata)(nil), // 2: mailsession.v1.DeliverMetadata
	(*DeliverResponse)(nil), // 3: mailsession.v1.DeliverResponse
}
var file_mailsession_v1_delivery_proto_depIdxs = []int32{
	2, // 0: mailsession.v1.DeliverRequest.metadata:type_name -> mailsession.v1.DeliverMetadata
	0, // 1: mailsession.v1.DeliverResponse.result:type_name -> mailsession.v1.DeliverResult
	1, // 2: mailsession.v1.DeliveryService.Deliver:input_type -> mailsession.v1.DeliverRequest
	3, // 3: mailsession.v1.DeliveryService.Deliver:output_type -> mailsession.v1.DeliverResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mailsession_v1_delivery_proto_init() }
func file_mailsession_v1_delivery_proto_init() {
	if File_mailsession_v1_delivery_proto != nil {
		return
	}
	file_mailsession_v1_delivery_proto_msgTypes[0].OneofWrappers = []any{
		(*DeliverRequest_Metadata)(nil),
		(*DeliverRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailsession_v1_delivery_proto_rawDesc), len(file_mailsession_v1_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailsession_v1_delivery_proto_goTypes,
		DependencyIndexes: file_mailsession_v1_delivery_proto_depIdxs,
		EnumInfos:         file_mailsession_v1_delivery_proto_enumTypes,
		MessageInfos:      file_mailsession_v1_delivery_proto_msgTypes,
	}.Build()
	File_mailsession_v1_delivery_proto = out.File
	file_mailsession_v1_delivery_proto_goTypes = nil
	file_mailsession_v1_delivery_proto_depIdxs = nil
}
