// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mailsession/v1/delivery.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_Deliver_FullMethodName = "/mailsession.v1.DeliveryService/Deliver"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeliveryService handles inbound message delivery (replaces mail-deliver binary).
// The delivery pipeline includes forwarding resolution, size checking, spam
// checking, sieve evaluation, and final maildir write.
type DeliveryServiceClient interface {
	// Deliver processes an inbound message through the full delivery pipeline.
	// Client-streaming: the first chunk carries delivery metadata (sender,
	// recipient, etc.), subsequent chunks carry the raw message body.
	Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DeliverRequest, DeliverResponse], error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DeliverRequest, DeliverResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_Deliver_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeliverRequest, DeliverResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_DeliverClient = grpc.ClientStreamingClient[DeliverRequest, DeliverResponse]

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
//
// DeliveryService handles inbound message delivery (replaces mail-deliver binary).
// The delivery pipeline includes forwarding resolution, size checking, spam
// checking, sieve evaluation, and final maildir write.
type DeliveryServiceServer interface {
	// Deliver processes an inbound message through the full delivery pipeline.
	// Client-streaming: the first chunk carries delivery metadata (sender,
	// recipient, etc.), subsequent chunks carry the raw message body.
	Deliver(grpc.ClientStreamingServer[DeliverRequest, DeliverResponse]) error
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) Deliver(grpc.ClientStreamingServer[DeliverRequest, DeliverResponse]) error {
	return status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_Deliver_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeliveryServiceServer).Deliver(&grpc.GenericServerStream[DeliverRequest, DeliverResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_DeliverServer = grpc.ClientStreamingServer[DeliverRequest, DeliverResponse]

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailsession.v1.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deliver",
			Handler:       _DeliveryService_Deliver_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mailsession/v1/delivery.proto",
}
