// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mailsession/v1/folders.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{0}
}

type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []string               `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{1}
}

func (x *ListFoldersResponse) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResponse) Reset() {
	*x = CreateFolderResponse{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResponse) ProtoMessage() {}

func (x *CreateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResponse.ProtoReflect.Descriptor instead.
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{3}
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderResponse) Reset() {
	*x = DeleteFolderResponse{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderResponse) ProtoMessage() {}

func (x *DeleteFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderResponse.ProtoReflect.Descriptor instead.
func (*DeleteFolderResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{5}
}

type RenameFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderRequest) Reset() {
	*x = RenameFolderRequest{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderRequest) ProtoMessage() {}

func (x *RenameFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderRequest.ProtoReflect.Descriptor instead.
func (*RenameFolderRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{6}
}

func (x *RenameFolderRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameFolderRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderResponse) Reset() {
	*x = RenameFolderResponse{}
	mi := &file_mailsession_v1_folders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderResponse) ProtoMessage() {}

func (x *RenameFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_folders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderResponse.ProtoReflect.Descriptor instead.
func (*RenameFolderResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_folders_proto_rawDescGZIP(), []int{7}
}

var File_mailsession_v1_folders_proto protoreflect.FileDescriptor

const file_mailsession_v1_folders_proto_rawDesc = "" +
	"\n" +
	"\x1cmailsession/v1/folders.proto\x12\x0emailsession.v1\"\x14\n" +
	"\x12ListFoldersRequest\"/\n" +
	"\x13ListFoldersResponse\x12\x18\n" +
	"\afolders\x18\x01 \x03(\tR\afolders\")\n" +
	"\x13CreateFolderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14CreateFolderResponse\")\n" +
	"\x13DeleteFolderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteFolderResponse\"K\n" +
	"\x13RenameFolderRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x16\n" +
	"\x14RenameFolderResponse2\xf8\x02\n" +
	"\rFolderService\x12V\n" +
	"\vListFolders\x12\".mailsession.v1.ListFoldersRequest\x1a#.mailsession.v1.ListFoldersResponse\x12Y\n" +
	"\fCreateFolder\x12#.mailsession.v1.CreateFolderRequest\x1a$.mailsession.v1.CreateFolderResponse\x12Y\n" +
	"\fDeleteFolder\x12#.mailsession.v1.DeleteFolderRequest\x1a$.mailsession.v1.DeleteFolderResponse\x12Y\n" +
	"\fRenameFolder\x12#.mailsession.v1.RenameFolderRequest\x1a$.mailsession.v1.RenameFolderResponseBMZKgithub.com/infodancer/maildancer/internal/mail-session/proto/mailsession/v1b\x06proto3"

var (
	file_mailsession_v1_folders_proto_rawDescOnce sync.Once
	file_mailsession_v1_folders_proto_rawDescData []byte
)

func file_mailsession_v1_folders_proto_rawDescGZIP() []byte {
	file_mailsession_v1_folders_proto_rawDescOnce.Do(func() {
		file_mailsession_v1_folders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailsession_v1_folders_proto_rawDesc), len(file_mailsession_v1_folders_proto_rawDesc)))
	})
	return file_mailsession_v1_folders_proto_rawDescData
}

var file_mailsession_v1_folders_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mailsession_v1_folders_proto_goTypes = []any{
	(*ListFoldersRequest)(nil),   // 0: mailsession.v1.ListFoldersRequest
	(*ListFoldersResponse)(nil),  // 1: mailsession.v1.ListFoldersResponse
	(*CreateFolderRequest)(nil),  // 2: mailsession.v1.CreateFolderRequest
	(*CreateFolderResponse)(nil), // 3: mailsession.v1.CreateFolderResponse
	(*DeleteFolderRequest)(nil),  // 4: mailsession.v1.DeleteFolderRequest
	(*DeleteFolderResponse)(nil), // 5: mailsession.v1.DeleteFolderResponse
	(*RenameFolderRequest)(nil),  // 6: mailsession.v1.RenameFolderRequest
	(*RenameFolderResponse)(nil), // 7: mailsession.v1.RenameFolderResponse
}
var file_mailsession_v1_folders_proto_depIdxs = []int32{
	0, // 0: mailsession.v1.FolderService.ListFolders:input_type -> mailsession.v1.ListFoldersRequest
	2, // 1: mailsession.v1.FolderService.CreateFolder:input_type -> mailsession.v1.CreateFolderRequest
	4, // 2: mailsession.v1.FolderService.DeleteFolder:input_type -> mailsession.v1.DeleteFolderRequest
	6, // 3: mailsession.v1.FolderService.RenameFolder:input_type -> mailsession.v1.RenameFolderRequest
	1, // 4: mailsession.v1.FolderService.ListFolders:output_type -> mailsession.v1.ListFoldersResponse
	3, // 5: mailsession.v1.FolderService.CreateFolder:output_type -> mailsession.v1.CreateFolderResponse
	5, // 6: mailsession.v1.FolderService.DeleteFolder:output_type -> mailsession.v1.DeleteFolderResponse
	7, // 7: mailsession.v1.FolderService.RenameFolder:output_type -> mailsession.v1.RenameFolderResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mailsession_v1_folders_proto_init() }
func file_mailsession_v1_folders_proto_init() {
	if File_mailsession_v1_folders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailsession_v1_folders_proto_rawDesc), len(file_mailsession_v1_folders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailsession_v1_folders_proto_goTypes,
		DependencyIndexes: file_mailsession_v1_folders_proto_depIdxs,
		MessageInfos:      file_mailsession_v1_folders_proto_msgTypes,
	}.Build()
	File_mailsession_v1_folders_proto = out.File
	file_mailsession_v1_folders_proto_goTypes = nil
	file_mailsession_v1_folders_proto_depIdxs = nil
}
