// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mailsession/v1/mailbox.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailboxService_List_FullMethodName          = "/mailsession.v1.MailboxService/List"
	MailboxService_Stat_FullMethodName          = "/mailsession.v1.MailboxService/Stat"
	MailboxService_Fetch_FullMethodName         = "/mailsession.v1.MailboxService/Fetch"
	MailboxService_FetchHeaders_FullMethodName  = "/mailsession.v1.MailboxService/FetchHeaders"
	MailboxService_SearchContent_FullMethodName = "/mailsession.v1.MailboxService/SearchContent"
	MailboxService_Append_FullMethodName        = "/mailsession.v1.MailboxService/Append"
	MailboxService_Copy_FullMethodName          = "/mailsession.v1.MailboxService/Copy"
	MailboxService_Move_FullMethodName          = "/mailsession.v1.MailboxService/Move"
	MailboxService_SetFlags_FullMethodName      = "/mailsession.v1.MailboxService/SetFlags"
	MailboxService_Expunge_FullMethodName       = "/mailsession.v1.MailboxService/Expunge"
	MailboxService_Rescan_FullMethodName        = "/mailsession.v1.MailboxService/Rescan"
	MailboxService_UIDValidity_FullMethodName   = "/mailsession.v1.MailboxService/UIDValidity"
	MailboxService_Delete_FullMethodName        = "/mailsession.v1.MailboxService/Delete"
	MailboxService_Undelete_FullMethodName      = "/mailsession.v1.MailboxService/Undelete"
	MailboxService_Commit_FullMethodName        = "/mailsession.v1.MailboxService/Commit"
)

// MailboxServiceClient is the client API for MailboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MailboxService handles message retrieval and management within a user's mailbox.
// All folder-scoped RPCs include the folder name in the request -- the server is
// stateless with respect to folder selection.
type MailboxServiceClient interface {
	// List returns metadata for all messages in a folder.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Stat returns the message count and total byte size for a folder.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Fetch retrieves the full message content. Server-streaming: the message
	// body is sent in 64KB chunks to avoid gRPC's default message size limit.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error)
	// FetchHeaders retrieves only the message headers (and optionally a few body lines).
	FetchHeaders(ctx context.Context, in *FetchHeadersRequest, opts ...grpc.CallOption) (*FetchHeadersResponse, error)
	// SearchContent evaluates content predicates server-side so that callers
	// (e.g. imapd SEARCH) never pull full message bodies across the proxy.
	// For each requested UID it returns the parsed header bytes (optional) and
	// per-term match booleans. The matching is protocol-agnostic substring
	// containment; callers compose their own query semantics (AND/OR/NOT) from
	// the results.
	SearchContent(ctx context.Context, in *SearchContentRequest, opts ...grpc.CallOption) (*SearchContentResponse, error)
	// Append stores a new message in a folder. Client-streaming: the first chunk
	// carries metadata (folder, flags, date), subsequent chunks carry message body.
	Append(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendRequest, AppendResponse], error)
	// Copy copies a message from one folder to another.
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	// Move moves a message between folders.
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	// SetFlags replaces the complete flag set on a message.
	SetFlags(ctx context.Context, in *SetFlagsRequest, opts ...grpc.CallOption) (*SetFlagsResponse, error)
	// Expunge permanently removes all messages with the \Deleted flag in a folder.
	Expunge(ctx context.Context, in *ExpungeRequest, opts ...grpc.CallOption) (*ExpungeResponse, error)
	// Rescan re-reads a folder and returns only newly appeared messages.
	Rescan(ctx context.Context, in *RescanRequest, opts ...grpc.CallOption) (*RescanResponse, error)
	// UIDValidity returns the IMAP UIDVALIDITY value for a folder.
	UIDValidity(ctx context.Context, in *UIDValidityRequest, opts ...grpc.CallOption) (*UIDValidityResponse, error)
	// Delete marks a message for POP3-style deletion.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Undelete clears a POP3-style deletion mark.
	Undelete(ctx context.Context, in *UndeleteRequest, opts ...grpc.CallOption) (*UndeleteResponse, error)
	// Commit applies all POP3-style pending deletions and exits.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type mailboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailboxServiceClient(cc grpc.ClientConnInterface) MailboxServiceClient {
	return &mailboxServiceClient{cc}
}

func (c *mailboxServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, MailboxService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, MailboxService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MailboxService_ServiceDesc.Streams[0], MailboxService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_FetchClient = grpc.ServerStreamingClient[FetchResponse]

func (c *mailboxServiceClient) FetchHeaders(ctx context.Context, in *FetchHeadersRequest, opts ...grpc.CallOption) (*FetchHeadersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchHeadersResponse)
	err := c.cc.Invoke(ctx, MailboxService_FetchHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) SearchContent(ctx context.Context, in *SearchContentRequest, opts ...grpc.CallOption) (*SearchContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContentResponse)
	err := c.cc.Invoke(ctx, MailboxService_SearchContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Append(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendRequest, AppendResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MailboxService_ServiceDesc.Streams[1], MailboxService_Append_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendRequest, AppendResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_AppendClient = grpc.ClientStreamingClient[AppendRequest, AppendResponse]

func (c *mailboxServiceClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, MailboxService_Copy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, MailboxService_Move_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) SetFlags(ctx context.Context, in *SetFlagsRequest, opts ...grpc.CallOption) (*SetFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFlagsResponse)
	err := c.cc.Invoke(ctx, MailboxService_SetFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Expunge(ctx context.Context, in *ExpungeRequest, opts ...grpc.CallOption) (*ExpungeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpungeResponse)
	err := c.cc.Invoke(ctx, MailboxService_Expunge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Rescan(ctx context.Context, in *RescanRequest, opts ...grpc.CallOption) (*RescanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescanResponse)
	err := c.cc.Invoke(ctx, MailboxService_Rescan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) UIDValidity(ctx context.Context, in *UIDValidityRequest, opts ...grpc.CallOption) (*UIDValidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIDValidityResponse)
	err := c.cc.Invoke(ctx, MailboxService_UIDValidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MailboxService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Undelete(ctx context.Context, in *UndeleteRequest, opts ...grpc.CallOption) (*UndeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteResponse)
	err := c.cc.Invoke(ctx, MailboxService_Undelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, MailboxService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailboxServiceServer is the server API for MailboxService service.
// All implementations must embed UnimplementedMailboxServiceServer
// for forward compatibility.
//
// MailboxService handles message retrieval and management within a user's mailbox.
// All folder-scoped RPCs include the folder name in the request -- the server is
// stateless with respect to folder selection.
type MailboxServiceServer interface {
	// List returns metadata for all messages in a folder.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Stat returns the message count and total byte size for a folder.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Fetch retrieves the full message content. Server-streaming: the message
	// body is sent in 64KB chunks to avoid gRPC's default message size limit.
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error
	// FetchHeaders retrieves only the message headers (and optionally a few body lines).
	FetchHeaders(context.Context, *FetchHeadersRequest) (*FetchHeadersResponse, error)
	// SearchContent evaluates content predicates server-side so that callers
	// (e.g. imapd SEARCH) never pull full message bodies across the proxy.
	// For each requested UID it returns the parsed header bytes (optional) and
	// per-term match booleans. The matching is protocol-agnostic substring
	// containment; callers compose their own query semantics (AND/OR/NOT) from
	// the results.
	SearchContent(context.Context, *SearchContentRequest) (*SearchContentResponse, error)
	// Append stores a new message in a folder. Client-streaming: the first chunk
	// carries metadata (folder, flags, date), subsequent chunks carry message body.
	Append(grpc.ClientStreamingServer[AppendRequest, AppendResponse]) error
	// Copy copies a message from one folder to another.
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	// Move moves a message between folders.
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
	// SetFlags replaces the complete flag set on a message.
	SetFlags(context.Context, *SetFlagsRequest) (*SetFlagsResponse, error)
	// Expunge permanently removes all messages with the \Deleted flag in a folder.
	Expunge(context.Context, *ExpungeRequest) (*ExpungeResponse, error)
	// Rescan re-reads a folder and returns only newly appeared messages.
	Rescan(context.Context, *RescanRequest) (*RescanResponse, error)
	// UIDValidity returns the IMAP UIDVALIDITY value for a folder.
	UIDValidity(context.Context, *UIDValidityRequest) (*UIDValidityResponse, error)
	// Delete marks a message for POP3-style deletion.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Undelete clears a POP3-style deletion mark.
	Undelete(context.Context, *UndeleteRequest) (*UndeleteResponse, error)
	// Commit applies all POP3-style pending deletions and exits.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	mustEmbedUnimplementedMailboxServiceServer()
}

// UnimplementedMailboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailboxServiceServer struct{}

func (UnimplementedMailboxServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMailboxServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedMailboxServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedMailboxServiceServer) FetchHeaders(context.Context, *FetchHeadersRequest) (*FetchHeadersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchHeaders not implemented")
}
func (UnimplementedMailboxServiceServer) SearchContent(context.Context, *SearchContentRequest) (*SearchContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContent not implemented")
}
func (UnimplementedMailboxServiceServer) Append(grpc.ClientStreamingServer[AppendRequest, AppendResponse]) error {
	return status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedMailboxServiceServer) Copy(context.Context, *CopyRequest) (*CopyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedMailboxServiceServer) Move(context.Context, *MoveRequest) (*MoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedMailboxServiceServer) SetFlags(context.Context, *SetFlagsRequest) (*SetFlagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFlags not implemented")
}
func (UnimplementedMailboxServiceServer) Expunge(context.Context, *ExpungeRequest) (*ExpungeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Expunge not implemented")
}
func (UnimplementedMailboxServiceServer) Rescan(context.Context, *RescanRequest) (*RescanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rescan not implemented")
}
func (UnimplementedMailboxServiceServer) UIDValidity(context.Context, *UIDValidityRequest) (*UIDValidityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UIDValidity not implemented")
}
func (UnimplementedMailboxServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMailboxServiceServer) Undelete(context.Context, *UndeleteRequest) (*UndeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Undelete not implemented")
}
func (UnimplementedMailboxServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedMailboxServiceServer) mustEmbedUnimplementedMailboxServiceServer() {}
func (UnimplementedMailboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeMailboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailboxServiceServer will
// result in compilation errors.
type UnsafeMailboxServiceServer interface {
	mustEmbedUnimplementedMailboxServiceServer()
}

func RegisterMailboxServiceServer(s grpc.ServiceRegistrar, srv MailboxServiceServer) {
	// If the following call panics, it indicates UnimplementedMailboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailboxService_ServiceDesc, srv)
}

func _MailboxService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MailboxServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_FetchServer = grpc.ServerStreamingServer[FetchResponse]

func _MailboxService_FetchHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).FetchHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_FetchHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).FetchHeaders(ctx, req.(*FetchHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_SearchContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).SearchContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_SearchContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).SearchContent(ctx, req.(*SearchContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Append_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MailboxServiceServer).Append(&grpc.GenericServerStream[AppendRequest, AppendResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_AppendServer = grpc.ClientStreamingServer[AppendRequest, AppendResponse]

func _MailboxService_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Copy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_SetFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).SetFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_SetFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).SetFlags(ctx, req.(*SetFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Expunge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpungeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Expunge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Expunge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Expunge(ctx, req.(*ExpungeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Rescan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Rescan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Rescan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Rescan(ctx, req.(*RescanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_UIDValidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIDValidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).UIDValidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_UIDValidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).UIDValidity(ctx, req.(*UIDValidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Undelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Undelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Undelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Undelete(ctx, req.(*UndeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailboxService_ServiceDesc is the grpc.ServiceDesc for MailboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailsession.v1.MailboxService",
	HandlerType: (*MailboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _MailboxService_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _MailboxService_Stat_Handler,
		},
		{
			MethodName: "FetchHeaders",
			Handler:    _MailboxService_FetchHeaders_Handler,
		},
		{
			MethodName: "SearchContent",
			Handler:    _MailboxService_SearchContent_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _MailboxService_Copy_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _MailboxService_Move_Handler,
		},
		{
			MethodName: "SetFlags",
			Handler:    _MailboxService_SetFlags_Handler,
		},
		{
			MethodName: "Expunge",
			Handler:    _MailboxService_Expunge_Handler,
		},
		{
			MethodName: "Rescan",
			Handler:    _MailboxService_Rescan_Handler,
		},
		{
			MethodName: "UIDValidity",
			Handler:    _MailboxService_UIDValidity_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MailboxService_Delete_Handler,
		},
		{
			MethodName: "Undelete",
			Handler:    _MailboxService_Undelete_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _MailboxService_Commit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _MailboxService_Fetch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Append",
			Handler:       _MailboxService_Append_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mailsession/v1/mailbox.proto",
}
