// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mailsession/v1/mailbox.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageInfo describes a single message in a folder.
type MessageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID is the msgstore-assigned unique identifier.
	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Size is the message size in bytes.
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Flags is the set of IMAP flags (e.g. \Seen, \Deleted, \Flagged).
	Flags         []string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{0}
}

func (x *MessageInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MessageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageInfo) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageInfo         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StatResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{5}
}

func (x *FetchRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *FetchRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type FetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message body chunk (up to 64KB per message).
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{6}
}

func (x *FetchResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FetchHeadersRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Folder string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Uid    uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// Number of body lines to include after headers. 0 = headers only.
	BodyLines     int32 `protobuf:"varint,3,opt,name=body_lines,json=bodyLines,proto3" json:"body_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHeadersRequest) Reset() {
	*x = FetchHeadersRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadersRequest) ProtoMessage() {}

func (x *FetchHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadersRequest.ProtoReflect.Descriptor instead.
func (*FetchHeadersRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{7}
}

func (x *FetchHeadersRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *FetchHeadersRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FetchHeadersRequest) GetBodyLines() int32 {
	if x != nil {
		return x.BodyLines
	}
	return 0
}

type FetchHeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []byte                 `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHeadersResponse) Reset() {
	*x = FetchHeadersResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadersResponse) ProtoMessage() {}

func (x *FetchHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadersResponse.ProtoReflect.Descriptor instead.
func (*FetchHeadersResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{8}
}

func (x *FetchHeadersResponse) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AppendRequest_Metadata
	//	*AppendRequest_Data
	Payload       isAppendRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{9}
}

func (x *AppendRequest) GetPayload() isAppendRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendRequest) GetMetadata() *AppendMetadata {
	if x != nil {
		if x, ok := x.Payload.(*AppendRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *AppendRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AppendRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isAppendRequest_Payload interface {
	isAppendRequest_Payload()
}

type AppendRequest_Metadata struct {
	// First message in the stream carries metadata.
	Metadata *AppendMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type AppendRequest_Data struct {
	// Subsequent messages carry body chunks.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*AppendRequest_Metadata) isAppendRequest_Payload() {}

func (*AppendRequest_Data) isAppendRequest_Payload() {}

type AppendMetadata struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Folder string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Flags  []string               `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	// Internal date as RFC 3339 string.
	Date          string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendMetadata) Reset() {
	*x = AppendMetadata{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMetadata) ProtoMessage() {}

func (x *AppendMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMetadata.ProtoReflect.Descriptor instead.
func (*AppendMetadata) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{10}
}

func (x *AppendMetadata) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *AppendMetadata) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *AppendMetadata) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UID assigned to the newly stored message.
	Uid           uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{11}
}

func (x *AppendResponse) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	DestFolder    string                 `protobuf:"bytes,3,opt,name=dest_folder,json=destFolder,proto3" json:"dest_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{12}
}

func (x *CopyRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *CopyRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CopyRequest) GetDestFolder() string {
	if x != nil {
		return x.DestFolder
	}
	return ""
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewUid        uint32                 `protobuf:"varint,1,opt,name=new_uid,json=newUid,proto3" json:"new_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{13}
}

func (x *CopyResponse) GetNewUid() uint32 {
	if x != nil {
		return x.NewUid
	}
	return 0
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SrcFolder     string                 `protobuf:"bytes,2,opt,name=src_folder,json=srcFolder,proto3" json:"src_folder,omitempty"`
	DestFolder    string                 `protobuf:"bytes,3,opt,name=dest_folder,json=destFolder,proto3" json:"dest_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{14}
}

func (x *MoveRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MoveRequest) GetSrcFolder() string {
	if x != nil {
		return x.SrcFolder
	}
	return ""
}

func (x *MoveRequest) GetDestFolder() string {
	if x != nil {
		return x.DestFolder
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewUid        uint32                 `protobuf:"varint,1,opt,name=new_uid,json=newUid,proto3" json:"new_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{15}
}

func (x *MoveResponse) GetNewUid() uint32 {
	if x != nil {
		return x.NewUid
	}
	return 0
}

type SetFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Flags         []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagsRequest) Reset() {
	*x = SetFlagsRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagsRequest) ProtoMessage() {}

func (x *SetFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagsRequest.ProtoReflect.Descriptor instead.
func (*SetFlagsRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{16}
}

func (x *SetFlagsRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *SetFlagsRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetFlagsRequest) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type SetFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagsResponse) Reset() {
	*x = SetFlagsResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagsResponse) ProtoMessage() {}

func (x *SetFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagsResponse.ProtoReflect.Descriptor instead.
func (*SetFlagsResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{17}
}

type ExpungeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpungeRequest) Reset() {
	*x = ExpungeRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpungeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpungeRequest) ProtoMessage() {}

func (x *ExpungeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpungeRequest.ProtoReflect.Descriptor instead.
func (*ExpungeRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{18}
}

func (x *ExpungeRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type ExpungeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UIDs of messages that were permanently removed.
	ExpelledUids  []uint32 `protobuf:"varint,1,rep,packed,name=expelled_uids,json=expelledUids,proto3" json:"expelled_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpungeResponse) Reset() {
	*x = ExpungeResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpungeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpungeResponse) ProtoMessage() {}

func (x *ExpungeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpungeResponse.ProtoReflect.Descriptor instead.
func (*ExpungeResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{19}
}

func (x *ExpungeResponse) GetExpelledUids() []uint32 {
	if x != nil {
		return x.ExpelledUids
	}
	return nil
}

type RescanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanRequest) Reset() {
	*x = RescanRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanRequest) ProtoMessage() {}

func (x *RescanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanRequest.ProtoReflect.Descriptor instead.
func (*RescanRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{20}
}

func (x *RescanRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type RescanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only messages that are new since the last List/Select/Rescan.
	NewMessages   []*MessageInfo `protobuf:"bytes,1,rep,name=new_messages,json=newMessages,proto3" json:"new_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanResponse) Reset() {
	*x = RescanResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanResponse) ProtoMessage() {}

func (x *RescanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanResponse.ProtoReflect.Descriptor instead.
func (*RescanResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{21}
}

func (x *RescanResponse) GetNewMessages() []*MessageInfo {
	if x != nil {
		return x.NewMessages
	}
	return nil
}

type UIDValidityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIDValidityRequest) Reset() {
	*x = UIDValidityRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIDValidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDValidityRequest) ProtoMessage() {}

func (x *UIDValidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDValidityRequest.ProtoReflect.Descriptor instead.
func (*UIDValidityRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{22}
}

func (x *UIDValidityRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type UIDValidityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UidValidity   uint32                 `protobuf:"varint,1,opt,name=uid_validity,json=uidValidity,proto3" json:"uid_validity,omitempty"`
	UidNext       uint32                 `protobuf:"varint,2,opt,name=uid_next,json=uidNext,proto3" json:"uid_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIDValidityResponse) Reset() {
	*x = UIDValidityResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIDValidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDValidityResponse) ProtoMessage() {}

func (x *UIDValidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDValidityResponse.ProtoReflect.Descriptor instead.
func (*UIDValidityResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{23}
}

func (x *UIDValidityResponse) GetUidValidity() uint32 {
	if x != nil {
		return x.UidValidity
	}
	return 0
}

func (x *UIDValidityResponse) GetUidNext() uint32 {
	if x != nil {
		return x.UidNext
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{25}
}

type UndeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteRequest) Reset() {
	*x = UndeleteRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteRequest) ProtoMessage() {}

func (x *UndeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteRequest.ProtoReflect.Descriptor instead.
func (*UndeleteRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{26}
}

func (x *UndeleteRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UndeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteResponse) Reset() {
	*x = UndeleteResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteResponse) ProtoMessage() {}

func (x *UndeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteResponse.ProtoReflect.Descriptor instead.
func (*UndeleteResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{27}
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{28}
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_mailbox_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_mailbox_proto_rawDescGZIP(), []int{29}
}

var File_mailsession_v1_mailbox_proto protoreflect.FileDescriptor

const file_mailsession_v1_mailbox_proto_rawDesc = "" +
	"\n" +
	"\x1cmailsession/v1/mailbox.proto\x12\x0emailsession.v1\"I\n" +
	"\vMessageInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"G\n" +
	"\fListResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.mailsession.v1.MessageInfoR\bmessages\"%\n" +
	"\vStatRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"E\n" +
	"\fStatResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\"8\n" +
	"\fFetchRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\"#\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"^\n" +
	"\x13FetchHeadersRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x1d\n" +
	"\n" +
	"body_lines\x18\x03 \x01(\x05R\tbodyLines\"0\n" +
	"\x14FetchHeadersResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x01(\fR\aheaders\"n\n" +
	"\rAppendRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.mailsession.v1.AppendMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"R\n" +
	"\x0eAppendMetadata\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x14\n" +
	"\x05flags\x18\x02 \x03(\tR\x05flags\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\"\n" +
	"\x0eAppendResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"X\n" +
	"\vCopyRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x1f\n" +
	"\vdest_folder\x18\x03 \x01(\tR\n" +
	"destFolder\"'\n" +
	"\fCopyResponse\x12\x17\n" +
	"\anew_uid\x18\x01 \x01(\rR\x06newUid\"_\n" +
	"\vMoveRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1d\n" +
	"\n" +
	"src_folder\x18\x02 \x01(\tR\tsrcFolder\x12\x1f\n" +
	"\vdest_folder\x18\x03 \x01(\tR\n" +
	"destFolder\"'\n" +
	"\fMoveResponse\x12\x17\n" +
	"\anew_uid\x18\x01 \x01(\rR\x06newUid\"Q\n" +
	"\x0fSetFlagsRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\"\x12\n" +
	"\x10SetFlagsResponse\"(\n" +
	"\x0eExpungeRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"6\n" +
	"\x0fExpungeResponse\x12#\n" +
	"\rexpelled_uids\x18\x01 \x03(\rR\fexpelledUids\"'\n" +
	"\rRescanRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"P\n" +
	"\x0eRescanResponse\x12>\n" +
	"\fnew_messages\x18\x01 \x03(\v2\x1b.mailsession.v1.MessageInfoR\vnewMessages\",\n" +
	"\x12UIDValidityRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"S\n" +
	"\x13UIDValidityResponse\x12!\n" +
	"\fuid_validity\x18\x01 \x01(\rR\vuidValidity\x12\x19\n" +
	"\buid_next\x18\x02 \x01(\rR\auidNext\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"\x10\n" +
	"\x0eDeleteResponse\"#\n" +
	"\x0fUndeleteRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"\x12\n" +
	"\x10UndeleteResponse\"\x0f\n" +
	"\rCommitRequest\"\x10\n" +
	"\x0eCommitResponse2\xa7\b\n" +
	"\x0eMailboxService\x12A\n" +
	"\x04List\x12\x1b.mailsession.v1.ListRequest\x1a\x1c.mailsession.v1.ListResponse\x12A\n" +
	"\x04Stat\x12\x1b.mailsession.v1.StatRequest\x1a\x1c.mailsession.v1.StatResponse\x12F\n" +
	"\x05Fetch\x12\x1c.mailsession.v1.FetchRequest\x1a\x1d.mailsession.v1.FetchResponse0\x01\x12Y\n" +
	"\fFetchHeaders\x12#.mailsession.v1.FetchHeadersRequest\x1a$.mailsession.v1.FetchHeadersResponse\x12I\n" +
	"\x06Append\x12\x1d.mailsession.v1.AppendRequest\x1a\x1e.mailsession.v1.AppendResponse(\x01\x12A\n" +
	"\x04Copy\x12\x1b.mailsession.v1.CopyRequest\x1a\x1c.mailsession.v1.CopyResponse\x12A\n" +
	"\x04Move\x12\x1b.mailsession.v1.MoveRequest\x1a\x1c.mailsession.v1.MoveResponse\x12M\n" +
	"\bSetFlags\x12\x1f.mailsession.v1.SetFlagsRequest\x1a .mailsession.v1.SetFlagsResponse\x12J\n" +
	"\aExpunge\x12\x1e.mailsession.v1.ExpungeRequest\x1a\x1f.mailsession.v1.ExpungeResponse\x12G\n" +
	"\x06Rescan\x12\x1d.mailsession.v1.RescanRequest\x1a\x1e.mailsession.v1.RescanResponse\x12V\n" +
	"\vUIDValidity\x12\".mailsession.v1.UIDValidityRequest\x1a#.mailsession.v1.UIDValidityResponse\x12G\n" +
	"\x06Delete\x12\x1d.mailsession.v1.DeleteRequest\x1a\x1e.mailsession.v1.DeleteResponse\x12M\n" +
	"\bUndelete\x12\x1f.mailsession.v1.UndeleteRequest\x1a .mailsession.v1.UndeleteResponse\x12G\n" +
	"\x06Commit\x12\x1d.mailsession.v1.CommitRequest\x1a\x1e.mailsession.v1.CommitResponseBMZKgithub.com/infodancer/maildancer/internal/mail-session/proto/mailsession/v1b\x06proto3"

var (
	file_mailsession_v1_mailbox_proto_rawDescOnce sync.Once
	file_mailsession_v1_mailbox_proto_rawDescData []byte
)

func file_mailsession_v1_mailbox_proto_rawDescGZIP() []byte {
	file_mailsession_v1_mailbox_proto_rawDescOnce.Do(func() {
		file_mailsession_v1_mailbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailsession_v1_mailbox_proto_rawDesc), len(file_mailsession_v1_mailbox_proto_rawDesc)))
	})
	return file_mailsession_v1_mailbox_proto_rawDescData
}

var file_mailsession_v1_mailbox_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_mailsession_v1_mailbox_proto_goTypes = []any{
	(*MessageInfo)(nil),          // 0: mailsession.v1.MessageInfo
	(*ListRequest)(nil),          // 1: mailsession.v1.ListRequest
	(*ListResponse)(nil),         // 2: mailsession.v1.ListResponse
	(*StatRequest)(nil),          // 3: mailsession.v1.StatRequest
	(*StatResponse)(nil),         // 4: mailsession.v1.StatResponse
	(*FetchRequest)(nil),         // 5: mailsession.v1.FetchRequest
	(*FetchResponse)(nil),        // 6: mailsession.v1.FetchResponse
	(*FetchHeadersRequest)(nil),  // 7: mailsession.v1.FetchHeadersRequest
	(*FetchHeadersResponse)(nil), // 8: mailsession.v1.FetchHeadersResponse
	(*AppendRequest)(nil),        // 9: mailsession.v1.AppendRequest
	(*AppendMetadata)(nil),       // 10: mailsession.v1.AppendMetadata
	(*AppendResponse)(nil),       // 11: mailsession.v1.AppendResponse
	(*CopyRequest)(nil),          // 12: mailsession.v1.CopyRequest
	(*CopyResponse)(nil),         // 13: mailsession.v1.CopyResponse
	(*MoveRequest)(nil),          // 14: mailsession.v1.MoveRequest
	(*MoveResponse)(nil),         // 15: mailsession.v1.MoveResponse
	(*SetFlagsRequest)(nil),      // 16: mailsession.v1.SetFlagsRequest
	(*SetFlagsResponse)(nil),     // 17: mailsession.v1.SetFlagsResponse
	(*ExpungeRequest)(nil),       // 18: mailsession.v1.ExpungeRequest
	(*ExpungeResponse)(nil),      // 19: mailsession.v1.ExpungeResponse
	(*RescanRequest)(nil),        // 20: mailsession.v1.RescanRequest
	(*RescanResponse)(nil),       // 21: mailsession.v1.RescanResponse
	(*UIDValidityRequest)(nil),   // 22: mailsession.v1.UIDValidityRequest
	(*UIDValidityResponse)(nil),  // 23: mailsession.v1.UIDValidityResponse
	(*DeleteRequest)(nil),        // 24: mailsession.v1.DeleteRequest
	(*DeleteResponse)(nil),       // 25: mailsession.v1.DeleteResponse
	(*UndeleteRequest)(nil),      // 26: mailsession.v1.UndeleteRequest
	(*UndeleteResponse)(nil),     // 27: mailsession.v1.UndeleteResponse
	(*CommitRequest)(nil),        // 28: mailsession.v1.CommitRequest
	(*CommitResponse)(nil),       // 29: mailsession.v1.CommitResponse
}
var file_mailsession_v1_mailbox_proto_depIdxs = []int32{
	0,  // 0: mailsession.v1.ListResponse.messages:type_name -> mailsession.v1.MessageInfo
	10, // 1: mailsession.v1.AppendRequest.metadata:type_name -> mailsession.v1.AppendMetadata
	0,  // 2: mailsession.v1.RescanResponse.new_messages:type_name -> mailsession.v1.MessageInfo
	1,  // 3: mailsession.v1.MailboxService.List:input_type -> mailsession.v1.ListRequest
	3,  // 4: mailsession.v1.MailboxService.Stat:input_type -> mailsession.v1.StatRequest
	5,  // 5: mailsession.v1.MailboxService.Fetch:input_type -> mailsession.v1.FetchRequest
	7,  // 6: mailsession.v1.MailboxService.FetchHeaders:input_type -> mailsession.v1.FetchHeadersRequest
	9,  // 7: mailsession.v1.MailboxService.Append:input_type -> mailsession.v1.AppendRequest
	12, // 8: mailsession.v1.MailboxService.Copy:input_type -> mailsession.v1.CopyRequest
	14, // 9: mailsession.v1.MailboxService.Move:input_type -> mailsession.v1.MoveRequest
	16, // 10: mailsession.v1.MailboxService.SetFlags:input_type -> mailsession.v1.SetFlagsRequest
	18, // 11: mailsession.v1.MailboxService.Expunge:input_type -> mailsession.v1.ExpungeRequest
	20, // 12: mailsession.v1.MailboxService.Rescan:input_type -> mailsession.v1.RescanRequest
	22, // 13: mailsession.v1.MailboxService.UIDValidity:input_type -> mailsession.v1.UIDValidityRequest
	24, // 14: mailsession.v1.MailboxService.Delete:input_type -> mailsession.v1.DeleteRequest
	26, // 15: mailsession.v1.MailboxService.Undelete:input_type -> mailsession.v1.UndeleteRequest
	28, // 16: mailsession.v1.MailboxService.Commit:input_type -> mailsession.v1.CommitRequest
	2,  // 17: mailsession.v1.MailboxService.List:output_type -> mailsession.v1.ListResponse
	4,  // 18: mailsession.v1.MailboxService.Stat:output_type -> mailsession.v1.StatResponse
	6,  // 19: mailsession.v1.MailboxService.Fetch:output_type -> mailsession.v1.FetchResponse
	8,  // 20: mailsession.v1.MailboxService.FetchHeaders:output_type -> mailsession.v1.FetchHeadersResponse
	11, // 21: mailsession.v1.MailboxService.Append:output_type -> mailsession.v1.AppendResponse
	13, // 22: mailsession.v1.MailboxService.Copy:output_type -> mailsession.v1.CopyResponse
	15, // 23: mailsession.v1.MailboxService.Move:output_type -> mailsession.v1.MoveResponse
	17, // 24: mailsession.v1.MailboxService.SetFlags:output_type -> mailsession.v1.SetFlagsResponse
	19, // 25: mailsession.v1.MailboxService.Expunge:output_type -> mailsession.v1.ExpungeResponse
	21, // 26: mailsession.v1.MailboxService.Rescan:output_type -> mailsession.v1.RescanResponse
	23, // 27: mailsession.v1.MailboxService.UIDValidity:output_type -> mailsession.v1.UIDValidityResponse
	25, // 28: mailsession.v1.MailboxService.Delete:output_type -> mailsession.v1.DeleteResponse
	27, // 29: mailsession.v1.MailboxService.Undelete:output_type -> mailsession.v1.UndeleteResponse
	29, // 30: mailsession.v1.MailboxService.Commit:output_type -> mailsession.v1.CommitResponse
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mailsession_v1_mailbox_proto_init() }
func file_mailsession_v1_mailbox_proto_init() {
	if File_mailsession_v1_mailbox_proto != nil {
		return
	}
	file_mailsession_v1_mailbox_proto_msgTypes[9].OneofWrappers = []any{
		(*AppendRequest_Metadata)(nil),
		(*AppendRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailsession_v1_mailbox_proto_rawDesc), len(file_mailsession_v1_mailbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailsession_v1_mailbox_proto_goTypes,
		DependencyIndexes: file_mailsession_v1_mailbox_proto_depIdxs,
		MessageInfos:      file_mailsession_v1_mailbox_proto_msgTypes,
	}.Build()
	File_mailsession_v1_mailbox_proto = out.File
	file_mailsession_v1_mailbox_proto_goTypes = nil
	file_mailsession_v1_mailbox_proto_depIdxs = nil
}
