// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mailsession/v1/outbound.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutboundService_Enqueue_FullMethodName = "/mailsession.v1.OutboundService/Enqueue"
)

// OutboundServiceClient is the client API for OutboundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OutboundService handles outbound message queue injection.
// Implemented by session-manager to centralize DKIM signing, envelope
// generation, and VERP computation for all protocol daemons (smtpd, sdmp, scmp).
type OutboundServiceClient interface {
	// Enqueue accepts an outbound message and writes it to the mail queue.
	// Client-streaming: the first chunk carries envelope metadata (sender,
	// recipients), subsequent chunks carry the raw message body.
	// No session token required -- access controlled by socket perms / mTLS
	// (same model as DeliveryService).
	Enqueue(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnqueueRequest, EnqueueResponse], error)
}

type outboundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutboundServiceClient(cc grpc.ClientConnInterface) OutboundServiceClient {
	return &outboundServiceClient{cc}
}

func (c *outboundServiceClient) Enqueue(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnqueueRequest, EnqueueResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OutboundService_ServiceDesc.Streams[0], OutboundService_Enqueue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnqueueRequest, EnqueueResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OutboundService_EnqueueClient = grpc.ClientStreamingClient[EnqueueRequest, EnqueueResponse]

// OutboundServiceServer is the server API for OutboundService service.
// All implementations must embed UnimplementedOutboundServiceServer
// for forward compatibility.
//
// OutboundService handles outbound message queue injection.
// Implemented by session-manager to centralize DKIM signing, envelope
// generation, and VERP computation for all protocol daemons (smtpd, sdmp, scmp).
type OutboundServiceServer interface {
	// Enqueue accepts an outbound message and writes it to the mail queue.
	// Client-streaming: the first chunk carries envelope metadata (sender,
	// recipients), subsequent chunks carry the raw message body.
	// No session token required -- access controlled by socket perms / mTLS
	// (same model as DeliveryService).
	Enqueue(grpc.ClientStreamingServer[EnqueueRequest, EnqueueResponse]) error
	mustEmbedUnimplementedOutboundServiceServer()
}

// UnimplementedOutboundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutboundServiceServer struct{}

func (UnimplementedOutboundServiceServer) Enqueue(grpc.ClientStreamingServer[EnqueueRequest, EnqueueResponse]) error {
	return status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedOutboundServiceServer) mustEmbedUnimplementedOutboundServiceServer() {}
func (UnimplementedOutboundServiceServer) testEmbeddedByValue()                         {}

// UnsafeOutboundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutboundServiceServer will
// result in compilation errors.
type UnsafeOutboundServiceServer interface {
	mustEmbedUnimplementedOutboundServiceServer()
}

func RegisterOutboundServiceServer(s grpc.ServiceRegistrar, srv OutboundServiceServer) {
	// If the following call panics, it indicates UnimplementedOutboundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutboundService_ServiceDesc, srv)
}

func _OutboundService_Enqueue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OutboundServiceServer).Enqueue(&grpc.GenericServerStream[EnqueueRequest, EnqueueResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OutboundService_EnqueueServer = grpc.ClientStreamingServer[EnqueueRequest, EnqueueResponse]

// OutboundService_ServiceDesc is the grpc.ServiceDesc for OutboundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutboundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailsession.v1.OutboundService",
	HandlerType: (*OutboundServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Enqueue",
			Handler:       _OutboundService_Enqueue_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mailsession/v1/outbound.proto",
}
