// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mailsession/v1/outbound.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnqueueRequest is client-streaming: metadata first, then body chunks.
type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EnqueueRequest_Metadata
	//	*EnqueueRequest_Data
	Payload       isEnqueueRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_mailsession_v1_outbound_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_outbound_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_outbound_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetPayload() isEnqueueRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetMetadata() *EnqueueMetadata {
	if x != nil {
		if x, ok := x.Payload.(*EnqueueRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *EnqueueRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EnqueueRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isEnqueueRequest_Payload interface {
	isEnqueueRequest_Payload()
}

type EnqueueRequest_Metadata struct {
	// First message in the stream carries envelope metadata.
	Metadata *EnqueueMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type EnqueueRequest_Data struct {
	// Subsequent messages carry raw message body chunks.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*EnqueueRequest_Metadata) isEnqueueRequest_Payload() {}

func (*EnqueueRequest_Data) isEnqueueRequest_Payload() {}

// EnqueueMetadata carries the outbound envelope information.
type EnqueueMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender is the MAIL FROM address.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Recipients is the list of RCPT TO addresses (remote only).
	// One envelope per recipient is written to the queue.
	Recipients    []string `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueMetadata) Reset() {
	*x = EnqueueMetadata{}
	mi := &file_mailsession_v1_outbound_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueMetadata) ProtoMessage() {}

func (x *EnqueueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_outbound_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueMetadata.ProtoReflect.Descriptor instead.
func (*EnqueueMetadata) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_outbound_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueMetadata) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *EnqueueMetadata) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

// EnqueueResponse is the outcome of queue injection.
type EnqueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The assigned RFC 5322 Message-ID.
	MessageId     string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_mailsession_v1_outbound_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_outbound_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_outbound_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_mailsession_v1_outbound_proto protoreflect.FileDescriptor

const file_mailsession_v1_outbound_proto_rawDesc = "" +
	"\n" +
	"\x1dmailsession/v1/outbound.proto\x12\x0emailsession.v1\"p\n" +
	"\x0eEnqueueRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.mailsession.v1.EnqueueMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"I\n" +
	"\x0fEnqueueMetadata\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1e\n" +
	"\n" +
	"recipients\x18\x02 \x03(\tR\n" +
	"recipients\"0\n" +
	"\x0fEnqueueResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId2_\n" +
	"\x0fOutboundService\x12L\n" +
	"\aEnqueue\x12\x1e.mailsession.v1.EnqueueRequest\x1a\x1f.mailsession.v1.EnqueueResponse(\x01BMZKgithub.com/infodancer/maildancer/internal/mail-session/proto/mailsession/v1b\x06proto3"

var (
	file_mailsession_v1_outbound_proto_rawDescOnce sync.Once
	file_mailsession_v1_outbound_proto_rawDescData []byte
)

func file_mailsession_v1_outbound_proto_rawDescGZIP() []byte {
	file_mailsession_v1_outbound_proto_rawDescOnce.Do(func() {
		file_mailsession_v1_outbound_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailsession_v1_outbound_proto_rawDesc), len(file_mailsession_v1_outbound_proto_rawDesc)))
	})
	return file_mailsession_v1_outbound_proto_rawDescData
}

var file_mailsession_v1_outbound_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mailsession_v1_outbound_proto_goTypes = []any{
	(*EnqueueRequest)(nil),  // 0: mailsession.v1.EnqueueRequest
	(*EnqueueMetadata)(nil), // 1: mailsession.v1.EnqueueMetadata
	(*EnqueueResponse)(nil), // 2: mailsession.v1.EnqueueResponse
}
var file_mailsession_v1_outbound_proto_depIdxs = []int32{
	1, // 0: mailsession.v1.EnqueueRequest.metadata:type_name -> mailsession.v1.EnqueueMetadata
	0, // 1: mailsession.v1.OutboundService.Enqueue:input_type -> mailsession.v1.EnqueueRequest
	2, // 2: mailsession.v1.OutboundService.Enqueue:output_type -> mailsession.v1.EnqueueResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mailsession_v1_outbound_proto_init() }
func file_mailsession_v1_outbound_proto_init() {
	if File_mailsession_v1_outbound_proto != nil {
		return
	}
	file_mailsession_v1_outbound_proto_msgTypes[0].OneofWrappers = []any{
		(*EnqueueRequest_Metadata)(nil),
		(*EnqueueRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailsession_v1_outbound_proto_rawDesc), len(file_mailsession_v1_outbound_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailsession_v1_outbound_proto_goTypes,
		DependencyIndexes: file_mailsession_v1_outbound_proto_depIdxs,
		MessageInfos:      file_mailsession_v1_outbound_proto_msgTypes,
	}.Build()
	File_mailsession_v1_outbound_proto = out.File
	file_mailsession_v1_outbound_proto_goTypes = nil
	file_mailsession_v1_outbound_proto_depIdxs = nil
}
