// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mailsession/v1/watch.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Folder to watch for changes.
	Folder        string `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_mailsession_v1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

// WatchEvent is pushed from server to client when folder contents change.
type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchEvent_NewMessages
	//	*WatchEvent_Expunged
	//	*WatchEvent_FlagsChanged
	Event         isWatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_mailsession_v1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchEvent) GetEvent() isWatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEvent) GetNewMessages() *NewMessagesEvent {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_NewMessages); ok {
			return x.NewMessages
		}
	}
	return nil
}

func (x *WatchEvent) GetExpunged() *ExpungedEvent {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Expunged); ok {
			return x.Expunged
		}
	}
	return nil
}

func (x *WatchEvent) GetFlagsChanged() *FlagsChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_FlagsChanged); ok {
			return x.FlagsChanged
		}
	}
	return nil
}

type isWatchEvent_Event interface {
	isWatchEvent_Event()
}

type WatchEvent_NewMessages struct {
	// New messages appeared in the folder.
	NewMessages *NewMessagesEvent `protobuf:"bytes,1,opt,name=new_messages,json=newMessages,proto3,oneof"`
}

type WatchEvent_Expunged struct {
	// Messages were expunged from the folder.
	Expunged *ExpungedEvent `protobuf:"bytes,2,opt,name=expunged,proto3,oneof"`
}

type WatchEvent_FlagsChanged struct {
	// Message flags changed.
	FlagsChanged *FlagsChangedEvent `protobuf:"bytes,3,opt,name=flags_changed,json=flagsChanged,proto3,oneof"`
}

func (*WatchEvent_NewMessages) isWatchEvent_Event() {}

func (*WatchEvent_Expunged) isWatchEvent_Event() {}

func (*WatchEvent_FlagsChanged) isWatchEvent_Event() {}

// NewMessagesEvent reports new messages in a watched folder.
type NewMessagesEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reuses MessageInfo from mailbox.proto.
	Messages      []*MessageInfo `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessagesEvent) Reset() {
	*x = NewMessagesEvent{}
	mi := &file_mailsession_v1_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessagesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessagesEvent) ProtoMessage() {}

func (x *NewMessagesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessagesEvent.ProtoReflect.Descriptor instead.
func (*NewMessagesEvent) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_watch_proto_rawDescGZIP(), []int{2}
}

func (x *NewMessagesEvent) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ExpungedEvent reports UIDs that were permanently removed.
type ExpungedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []string               `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpungedEvent) Reset() {
	*x = ExpungedEvent{}
	mi := &file_mailsession_v1_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpungedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpungedEvent) ProtoMessage() {}

func (x *ExpungedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpungedEvent.ProtoReflect.Descriptor instead.
func (*ExpungedEvent) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_watch_proto_rawDescGZIP(), []int{3}
}

func (x *ExpungedEvent) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

// FlagsChangedEvent reports a message whose flags were updated.
type FlagsChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Flags         []string               `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagsChangedEvent) Reset() {
	*x = FlagsChangedEvent{}
	mi := &file_mailsession_v1_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagsChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagsChangedEvent) ProtoMessage() {}

func (x *FlagsChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mailsession_v1_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagsChangedEvent.ProtoReflect.Descriptor instead.
func (*FlagsChangedEvent) Descriptor() ([]byte, []int) {
	return file_mailsession_v1_watch_proto_rawDescGZIP(), []int{4}
}

func (x *FlagsChangedEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FlagsChangedEvent) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

var File_mailsession_v1_watch_proto protoreflect.FileDescriptor

const file_mailsession_v1_watch_proto_rawDesc = "" +
	"\n" +
	"\x1amailsession/v1/watch.proto\x12\x0emailsession.v1\x1a\x1cmailsession/v1/mailbox.proto\"&\n" +
	"\fWatchRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"\xe3\x01\n" +
	"\n" +
	"WatchEvent\x12E\n" +
	"\fnew_messages\x18\x01 \x01(\v2 .mailsession.v1.NewMessagesEventH\x00R\vnewMessages\x12;\n" +
	"\bexpunged\x18\x02 \x01(\v2\x1d.mailsession.v1.ExpungedEventH\x00R\bexpunged\x12H\n" +
	"\rflags_changed\x18\x03 \x01(\v2!.mailsession.v1.FlagsChangedEventH\x00R\fflagsChangedB\a\n" +
	"\x05event\"K\n" +
	"\x10NewMessagesEvent\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.mailsession.v1.MessageInfoR\bmessages\"#\n" +
	"\rExpungedEvent\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\tR\x04uids\";\n" +
	"\x11FlagsChangedEvent\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05flags\x18\x02 \x03(\tR\x05flags2S\n" +
	"\fWatchService\x12C\n" +
	"\x05Watch\x12\x1c.mailsession.v1.WatchRequest\x1a\x1a.mailsession.v1.WatchEvent0\x01B9Z7github.com/infodancer/maildancer/internal/mail-session/proto/mailsession/v1b\x06proto3"

var (
	file_mailsession_v1_watch_proto_rawDescOnce sync.Once
	file_mailsession_v1_watch_proto_rawDescData []byte
)

func file_mailsession_v1_watch_proto_rawDescGZIP() []byte {
	file_mailsession_v1_watch_proto_rawDescOnce.Do(func() {
		file_mailsession_v1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailsession_v1_watch_proto_rawDesc), len(file_mailsession_v1_watch_proto_rawDesc)))
	})
	return file_mailsession_v1_watch_proto_rawDescData
}

var file_mailsession_v1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mailsession_v1_watch_proto_goTypes = []any{
	(*WatchRequest)(nil),      // 0: mailsession.v1.WatchRequest
	(*WatchEvent)(nil),        // 1: mailsession.v1.WatchEvent
	(*NewMessagesEvent)(nil),  // 2: mailsession.v1.NewMessagesEvent
	(*ExpungedEvent)(nil),     // 3: mailsession.v1.ExpungedEvent
	(*FlagsChangedEvent)(nil), // 4: mailsession.v1.FlagsChangedEvent
	(*MessageInfo)(nil),       // 5: mailsession.v1.MessageInfo
}
var file_mailsession_v1_watch_proto_depIdxs = []int32{
	2, // 0: mailsession.v1.WatchEvent.new_messages:type_name -> mailsession.v1.NewMessagesEvent
	3, // 1: mailsession.v1.WatchEvent.expunged:type_name -> mailsession.v1.ExpungedEvent
	4, // 2: mailsession.v1.WatchEvent.flags_changed:type_name -> mailsession.v1.FlagsChangedEvent
	5, // 3: mailsession.v1.NewMessagesEvent.messages:type_name -> mailsession.v1.MessageInfo
	0, // 4: mailsession.v1.WatchService.Watch:input_type -> mailsession.v1.WatchRequest
	1, // 5: mailsession.v1.WatchService.Watch:output_type -> mailsession.v1.WatchEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mailsession_v1_watch_proto_init() }
func file_mailsession_v1_watch_proto_init() {
	if File_mailsession_v1_watch_proto != nil {
		return
	}
	file_mailsession_v1_mailbox_proto_init()
	file_mailsession_v1_watch_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchEvent_NewMessages)(nil),
		(*WatchEvent_Expunged)(nil),
		(*WatchEvent_FlagsChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailsession_v1_watch_proto_rawDesc), len(file_mailsession_v1_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailsession_v1_watch_proto_goTypes,
		DependencyIndexes: file_mailsession_v1_watch_proto_depIdxs,
		MessageInfos:      file_mailsession_v1_watch_proto_msgTypes,
	}.Build()
	File_mailsession_v1_watch_proto = out.File
	file_mailsession_v1_watch_proto_goTypes = nil
	file_mailsession_v1_watch_proto_depIdxs = nil
}
